### ISSUE TITLE
Can't use the repo.

### ISSUE THREAD

**Issue by kaiyes** [ttdung11t2/react-native-password-strength-checker#8]
Hi, 
Can't seem to use the repo after following the instructions, I.E=> import the lib and then in the render() function, use the supplied code ```  <PasswordStrength
                secureTextEntry
                minLength={4}
                ruleNames="symbols|words"
                strengthLevels={strengthLevels}
                minLevel={0}
                barWidthPercent={65}
                showBarOnEmpty={true}
                barColor="#ccc"
                onChangeText={(text, isValid) =>
                  this.setState({
                    password: {
                      value: text,
                      isValid: isValid
                    }
                  })
                }
              />``` 
![simulator screen shot - iphone 6 - 2018-10-04 at 11 26 21](https://user-images.githubusercontent.com/5293742/46454565-88f5d900-c7c8-11e8-8c24-46b43c59b8c7.png)

**Comment by kaiyes** [comment]
Also, just tested after removing all the code related to the repo. Even only the import line causes the issue. So I guess there are issues with the lib. Using 
```
    "react": "16.4.1",
    "react-native": "0.56.0",
```

**Comment by mjeries** [comment]
Might be a dupe of #1. See my PR #5.

**Comment by kaiyes** [comment]
was able to handle the issue by using another excellent password checker where I implemented the UI myself https://github.com/dropbox/zxcvbn
